version: 2 # Version du format de configuration Dependabot (toujours 2)
updates:
  - package-ecosystem: "npm" # Surveille express, sql.js, lodash, moment (dependences) ET eslint, jest, supertest (devDependencies) dans le package.json. Si une nouvelle version sort, Dependabot ouvre automatiquement une Pull Request sur GitHub pour mettre à jour
    directory: "/CI-CD" # Dossier où se trouve le package.json
    schedule:
      interval: "weekly" # Vérifie une fois par semaine